---
- defaults:
    link:
      create: true
      relink: true
      force: true
- link:
    "~/.config/zathura": apps/zathura
    "~/.config/ranger": apps/ranger
    "~/.config/papis": apps/papis
    "~/.config/broot": apps/broot
