---
- defaults:
    link:
      create: true
      relink: true
      force: true
- link:
    "~/.editorconfig": development/editorconfig
    "~/.astylerc": development/astylerc
    "~/.gitconfig": development/gitconfig
    "~/.global_gitignore": development/global_gitignore
    "~/.config/bat": development/bat
    "~/.config/ripgrep": development/ripgrep
