---
- defaults:
    link:
      create: true
      relink: true
- clean:
    - "~"
- rust:
    - stable:
        - targets:
            - x86_64-apple-darwin
            - x86_64-unknown-linux-gnu
            - x86_64-unknown-linux-musl
        - components:
            - rust-analysis
            - rls
            - rust-src
    - nightly:
        - targets:
            - x86_64-apple-darwin
            - x86_64-unknown-linux-gnu
            - x86_64-unknown-linux-musl
        - components:
            - rust-analysis
            - rls
            - rust-src

- shell:
    - command: scripts/install-rust
      description: Installing rust
      stdout: true

- cargo:
    - bat
    - broot
    - cargo-update
    - diskus
    - exa
    - fd-find
    - find-files
    - grex
    - lsd
    - organize-rt
    - rargs
    - record-query
    - ripgrep
    - sd
    - skim
    - spt
    - starship
    - topgrade
    - watchexec
    - xsv
    - ytop
