---
- defaults:
    link:
      create: true
      relink: true
      force: true
- link:
    "~/.zshrc": shells/zshrc
    "~/.zsh": shells/zsh
    "~/.zprofile": shells/zprofile
    "~/.zshenv": shells/zshenv
    "~/.inputrc": shells/inputrc
    "~/.editrc": shells/editrc
    "~/.dir_colors": shells/dir_colors
- shell:
    -
    description: Downloading zplug
    command: scripts/install-zplug
    -
    description: Setting Z-shell as default shell
    command: scripts/default-zsh
