#!/bin/zsh

umask 022
# Check if terminbal is dumb {{{
if [[ ${TERM} == 'dumb' ]]; then
    return
fi
#}}}
# Get operating system {{{
platform='unknown'
unamestr=$(uname)
if [[ $unamestr == 'Linux' ]]; then
  platform='linux'
elif [[ $unamestr == 'Darwin' ]]; then
  platform='darwin'
fi

# if [[ $platform == 'linux' ]]; then
#     if [[ ! -d /usr/share/zsh/scripts/zplug ]]; then
#       yaourt -S zplug
#     fi
#     source /usr/share/zsh/scripts/zplug/init.zsh
# elif [[ $platform == 'darwin' ]]; then
#     if [[ ! -d /usr/local/opt/zplug ]]; then
#         brew install zplug
#     fi
#     export ZPLUG_HOME=/usr/local/opt/zplug
#     source $ZPLUG_HOME/init.zsh
# fi
export ZPLUG_HOME=$HOME/.zplug
source $ZPLUG_HOME/init.zsh
# }}}
# Adding some variables {{{
export ZSH_TMUX_AUTOSTART=true
ENHANCD_FILTER="sk-tmux:sk:fzf-tmux:fzf:peco:percol:gof:pick:icepick:sentaku:selecta"
ENHANCD_COMMAND=cd
if (( $+commands[fd] )); then
  export FZF_CMD='fd --hidden --follow --no-ignore-vcs --exclude ".git/*" --exclude "node_modules/*"'
  export FZF_DEFAULT_COMMAND="$FZF_CMD --type f"
  export FZF_CTRL_T_COMMAND="$FZF_CMD"
  export FZF_ALT_C_COMMAND="$FZF_CMD --type d ."
elif (( $+commands[rg] )); then
  export FZF_CMD='rg --no-messages --no-ignore-vcs'
  export FZF_DEFAULT_COMMAND="$FZF_CMD --files"
  export FZF_CTRL_T_COMMAND="$FZF_CMD"
fi
export FZF_DEFAULT_OPTS='
--extended
--ansi
--multi
--bind=ctrl-u:page-up
--bind=ctrl-d:page-down
--bind=ctrl-z:toggle-all
'
fpath=(~/.zsh/completion(N-/) $fpath)
eval "$(dircolors --sh "$HOME/.dir_colors/dircolors.ansi-dark")"
# }}}
# List of all the plugins + load the plugins {{{
zplug "b4b4r07/enhancd", use:init.sh
zplug "hlissner/zsh-autopair", defer:2
zplug "junegunn/fzf", use:"shell/*.zsh"
zplug "lotabout/skim", as:command, use:"bin/sk-tmux"
zplug "plugins/archlinux", from:oh-my-zsh
zplug "plugins/command-not-found", from:oh-my-zsh
zplug "plugins/git", from:oh-my-zsh
zplug "plugins/git-flow", from:oh-my-zsh
zplug "plugins/pip", from:oh-my-zsh
zplug "plugins/pipenv", from:oh-my-zsh
zplug "plugins/ripgrep", from:oh-my-zsh
zplug "plugins/rust", from:oh-my-zsh
zplug "plugins/tmux", from:oh-my-zsh
zplug "takaaki-kasai/git-foresta", as:command, use:"git-foresta"
zplug "zsh-users/zsh-autosuggestions"
zplug "zsh-users/zsh-completions"
zplug "zsh-users/zsh-history-substring-search", defer:3
zplug "zsh-users/zsh-syntax-highlighting", defer:1
zplug "~/.zsh", from:local, use:aliases.zsh
zplug "~/.zsh", from:local, use:completion.zsh
zplug "~/.zsh", from:local, use:keybinds.zsh, defer:2
zplug "~/.zsh", from:local, use:noglob.zsh
zplug "~/.zsh", from:local, use:setopt.zsh, defer:0
zplug "~/.zsh", from:local, use:spectrum.zsh
zplug "~/.zsh", from:local, use:sublime.zsh
zplug "~/.zsh", from:local, use:zmv.zsh
eval "$(starship init zsh)"
# Install plugins if there are plugins that have not been installed
if ! zplug check --verbose; then
    printf "Install? [y/N]: "
    if read -q; then
        echo; zplug install
    fi
fi

zplug load
# }}}
# Folding the .vimrc {{{
# vim:foldmethod=marker:foldlevel=0
# }}}

autoload bashcompinit
source ${VCPKG_ROOT}/scripts/vcpkg_completion.zsh
eval "$(atuin init zsh)"
